### PR TITLE
Add eslint, update deps

### PR DESCRIPTION
**Pull request by korywka**
* add eslint and fix
* update deps for latest nodejs version
*  use documentation.js 

Tests works, but Coverage doesn't :( Please fix who knows how travis works.

### CODE REVIEW

**Comment by mourner** [comment]
Thanks for taking on this, looks great to me! 

We might want to simply remove the coverage script (it isn't that useful). If you want to fix it, I think we should switch to a more recent tool like `nyc` (a successor to `istanbul`).

**Comment by korywka** [comment]
@mourner ✋ 

Added jest, it has coverage from the box. Do not know what to do with `.travis.yml` (it contains old version of nodejs).

**Comment by mourner** [comment]
Oh no! Can we please go back? As far I know no one used Jest at Mapbox, and it feels like quite an overkill for such a small, simple project. Let’s not change conventions / dependencies significantly without discussing this first.

**Comment by korywka** [comment]
You are right. Please, take a look when you have free time 😉

**Comment by mourner** [comment]
Thank you! Something weird is going on with CI setup but I'll try to figure it out...

**Comment by korywka** [comment]
Thank you. Do not know why `nyc` in both `dependencies` and `devDependecnies`. Please, remove it from `deps`: https://github.com/mapbox/point-geometry/blob/master/package.json#L39

Sorry.

**Pull request merged**
